Use isset() instead of null checks in unserialize()
This makes the code forward-compatible with typed properties, to prevent this error:
> Error: Typed property Brick\Math\BigInteger::$value must not be accessed before initialization

Also, redundant checks are removed from BigDecimal and BigRational: $value cannot be set without $scale, and $numerator cannot be set without $denominator.